config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/password', to: 'passwords#edit', as: 'password_edit'
  patch '/password', to: 'passwords#update'

  get '/password/reset', to: 'password_reset#new'
  post '/password/reset', to: 'password_reset#create'
  get '/password/reset/edit', to: 'password_reset#edit'
  patch '/password/reset/edit', to: 'password_reset#update'

  get '/about', to: 'about#index'

  get '/signup', to: 'user#new'
  post '/signup', to: 'user#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  root to: 'main#index'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# User Model
class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 2 }, allow_nil: false
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
   def index
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_session
  def current_session
    return unless session[:user_id]

    Current.user = User.find_by(id: session[:user_id])
  end

  def user_not_logged
    return  unless Current.user.nil?

    redirect_to login_path, alert: 'You must be logged in to continue'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      # mail
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path,
                notice: 'If an account with that email exists, we have sent the link to reset your password'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'reset_password')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to login_path, alert: 'Token is expired'
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'reset_password')
    if @user.update(password_params)
      redirect_to login_path, notice: 'Password has been updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :user_not_logged
  def edit; end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password has been updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash[:alert] = 'Invalid email or password'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>hi</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container max-w-7xl flex flex-col justify-center mt-2 mx-auto">
     <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="flex flex-col justify-center mt-2">
  <h1 class="text-4xl font-bold">Welcome home</h1>
  <div>
    <h3 class="text-2xl font-bold">
      <% if Current.user %>
        <%= Current.user.email %>
      <% end %>
    </h3>
  </div>
</div>

app/views/password_reset/edit.html.erb
<h1 class="text-4xl font-bold">Change password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), class: "flex flex-col w-full" do |form| %>
  <% if form.object.errors.any? %>
    <div class="m-2 p-5 w-full bg-red-500">
      <ul class="list-disc">
        <% form.object.errors.full_messages.each do |message| %>
          <li class="ml-3 text-red-900 my-1">
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="m-2 flex flex-col">
    <%= form.label :password %>
    <%= form.password_field :password, class: "border-2 border-black w-52 p-2", placeholder: "password" %>
  </div>
  <div class="m-2 flex flex-col">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "border-2 border-black w-52 p-2", placeholder: "password" %>
  </div>
  <div class="m-2">
    <%= form.submit "Update Password", class: "border-2 border-black p-3" %>
  </div>
<% end %>

app/views/password_reset/new.html.erb
<h1 class="text-4xl font-bold">Reset your password</h1>
<%= form_with url: password_reset_path, class: "flex flex-col w-full" do |form| %>
  <div class="m-2 flex flex-col">
    <%= form.label :email %>
    <%= form.email_field :email, class: "border-2 border-black w-52 p-2", placeholder: "Email@mail.com" %>
  </div>
  <div class="m-2">
    <%= form.submit "Reset Password", class: "border-2 border-black p-3" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="bg-blue-500 p-3 rounded w-full my-2 text-blue-900 font-bold" role="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="bg-red-500 p-3 rounded w-full my-2 text-red-900 font-bold" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class=" bg-white dark:bg-gray-800 ">
  <nav class="2xl:container 2xl:mx-auto sm:py-6 sm:px-7 py-5 px-4">
    <!-- For large and Medium-sized Screen -->
    <div class="flex justify-between ">
      <div class=" flex space-x-3 items-center">
        <img class="p-1 dark:bg-white rounded-full" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/header-3-svg5.svg" alt="circle" />
        <%= link_to "About", about_path, class: "font-normal text-2xl leading-6 text-gray-800 dark:text-white" %>
        <%= link_to "Home", root_path, class: "font-normal text-2xl leading-6 text-gray-800 dark:text-white" %>
      </div>
      <div class="hidden sm:flex flex-row space-x-4">
        <% if !Current.user %>
          <%= link_to "Sign up", signup_path, class: "rounded-md flex space-x-2 w-24 h-10 font-normal text-sm leading-3 text-indigo-700 bg-white border border-indigo-700 focus:outline-none focus:bg-gray-200 hover:bg-gray-200 duration-150 justify-center items-center" %>
          <%= link_to "Login", login_path, class: "rounded-md flex space-x-2 w-24 h-10 font-normal text-sm leading-3 text-indigo-700 bg-white border border-indigo-700 focus:outline-none focus:bg-gray-200 hover:bg-gray-200 duration-150 justify-center items-center" %>
        <% else %>
          <%= link_to Current.user.email, password_edit_path %>
          <%= button_to "Logout", logout_path, class: "rounded-md flex space-x-2 w-24 h-10 font-normal text-sm leading-3 text-indigo-700 bg-white border border-indigo-700 focus:outline-none focus:bg-gray-200 hover:bg-gray-200 duration-150 justify-center items-center", method: :delete %></button>
      <% end %>
    </div>
    <!-- Burger Icon -->
    <div id="bgIcon" onclick="toggleMenu()"  class="focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800  flex justify-center items-center sm:hidden cursor-pointer">
      <img class="dark:bg-white" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/header-3-svg6.svg" alt="burger" />
      <img class="dark:bg-white hidden" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/header-3-svg7.svg" alt="cross" />
    </div>
  </div>
  <!-- Mobile and small-screen devices (toggle Menu) -->
  <div id="MobileNavigation" class="hidden sm:hidden mt-4 mx-auto">
    <div class="flex flex-col gap-4 mt-4 w-80 mx-auto ">
      <button class="rounded-md flex space-x-2 w-full h-10 font-normal text-sm leading-3 text-indigo-700 bg-indigo-600 bg-opacity-0 hover:opacity-100 duration-100 border border-indigo-700 focus:outline-none focus:bg-gray-200 hover:bg-gray-200 duration-150 justify-center items-center" >Sign Up</button>
      <button class="rounded-md flex space-x-2 w-full h-10 font-normal text-sm leading-3 text-white bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 focus:bg-indigo-600 hover:bg-indigo-600 duration-150 justify-center items-center" >Sign In</button>
    </div>
  </div>
</nav>
</div>

app/views/user/new.html.erb
<h1 class="text-4xl font-bold">Signup form</h1>
<%= form_with model: @user, url: signup_path, class: "flex flex-col w-full" do |form| %>
  <% if form.object.errors.any? %>
    <div class="m-2 p-5 w-full bg-red-500">
      <ul class="list-disc">
        <% form.object.errors.full_messages.each do |message| %>
          <li class="ml-3 text-red-900 my-1">
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="m-2 flex flex-col">
    <%= form.label :email %>
    <%= form.email_field :email, class: "border-2 border-black w-52" %>
  </div>
  <div class="m-2 flex flex-col">
    <%= form.label :password %>
    <%= form.password_field :password, class: "border-2 border-black w-52" %>
  </div>
  <div class="m-2 flex flex-col">
    <%= form.label :password_confirmation, "Confirm password" %>
    <%= form.password_field :password_confirmation, class: "border-2 border-black w-52"%>
  </div>
  <%= link_to 'Forgot your password?', password_reset_path %>
  <div class="m-2">
    <%= form.submit "Sign up", class: "border-2 border-black p-3" %>
  </div>
<% end %>